<?php

namespace VIVA\DanceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PratiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PratiqueRepository extends EntityRepository
{
}
