<?php

namespace VIVA\DanceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Regelement_StageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Regelement_StageRepository extends EntityRepository
{
}
