<?php

namespace VIVA\DanceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Type_ReglementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_ReglementRepository extends EntityRepository
{
}
